[service]
service_name = "Cats"

[[service.entities]]
name = "Person"

[[service.entities.fields]]
name = "name"
scalar = "String"
required = true

[[service.entities.fields]]
name = "age"
scalar = "Int"
required = false

[[service.entities.fields]]
name = "married"
scalar = "Boolean"
required = true
