[service]
service_name = "espresso"

[[service.data_sources]]
[service.data_sources.SQL]
name = "espresso_db"
uri = "sqlite:/home/nickisyourfan/Desktop/DEV/sqlite_dbs/espresso.db"
dialect = "SQLITE"

[[service.entities]]
name = "Espresso"
[service.entities.data_source]
from = "espresso_db"
table = "espresso"

[[service.entities.fields]]
name = "id"
scalar= "Int"
required = true
exclude_from_input = ["CreateOne", "UpdateOne"]

[[service.entities.fields]]
name = "name"
scalar= "String"
required = true

[[service.entities.fields]]
name = "rating"
scalar= "Int"
required = true
