[service]
service_name = "friends"
port = 4050
log_level = "debug"

[[service.data_sources]]
[service.data_sources.Mongo]
name = "friends_data_source"
uri = "mongodb://sun:sun@127.0.0.1:27017/sun"
db = "sun"

[[service.entities]]
name = "user"

[[service.entities.fields]]
name = "_id"
scalar = "ObjectID"
required = true
exclude_from_input = ["CreateOne", "UpdateOne"]
[[service.entities.fields]]
name = "name"
scalar = "String"
required = true
[[service.entities.fields]]
name = "age"
scalar = "Int"
required = false
[[service.entities.fields]]
name = "married"
scalar = "Boolean"
required = true
[[service.entities.fields]]
name = "friends"
scalar = "ObjectID"
required = false
list = true
as_type = "user"


